
import type { NameOfAllah } from '../../../types';

export const NAMES_OF_ALLAH: NameOfAllah[] = [
  { id: 1, arabic: "الله", english: "Allah", meaning: "هو الاسم الجامع لمعاني الألوهية، المألوه المعبود المستحق للعبادة وحده." },
  { id: 2, arabic: "الرَّحْمَنُ", english: "Ar-Rahman", meaning: "ذي الرحمة الواسعة التي شملت جميع الخلائق." },
  { id: 3, arabic: "الرَّحِيمُ", english: "Ar-Raheem", meaning: "ذي الرحمة الواصلة للمؤمنين يوم القيامة." },
  { id: 4, arabic: "المَلِكُ", english: "Al-Malik", meaning: "المالك لجميع الأشياء، المتصرف فيها بلا ممانع ولا مدافع." },
  { id: 5, arabic: "القُدُّوسُ", english: "Al-Quddus", meaning: "المنزه عن كل نقص وعيب، وعن ما لا يليق بجلاله." },
  { id: 6, arabic: "السَّلَامُ", english: "As-Salam", meaning: "السالم من جميع العيوب والنقائص، والمسلم لعباده من الآفات." },
  { id: 7, arabic: "المُؤْمِنُ", english: "Al-Mu'min", meaning: "الذي صدق رسله وأيدهم بالمعجزات، والذي يأمن أولياءه من عذابه." },
  { id: 8, arabic: "المُهَيْمِنُ", english: "Al-Muhaymin", meaning: "الرقيب على كل شيء، الشاهد على خلقه بأعمالهم." },
  { id: 9, arabic: "العَزِيزُ", english: "Al-Aziz", meaning: "القوي الذي لا يغلب، الممتنع فلا ينال." },
  { id: 10, arabic: "الجَبَّارُ", english: "Al-Jabbar", meaning: "الذي يجبر الكسير، ويقهر الجبابرة، العالي فوق خلقه." },
  { id: 11, arabic: "المُتَكَبِّرُ", english: "Al-Mutakabbir", meaning: "المتعالي عن صفات الخلق، وعن كل سوء وظلم." },
  { id: 12, arabic: "الخَالِقُ", english: "Al-Khaliq", meaning: "الموجد للأشياء من العدم على غير مثال سابق." },
  { id: 13, arabic: "البَارِئُ", english: "Al-Bari'", meaning: "الذي خلق الخلق بريئاً من التفاوت والنقص." },
  { id: 14, arabic: "المُصَوِّرُ", english: "Al-Musawwir", meaning: "الذي صور المخلوقات وميزها عن بعضها بصور وهيئات مختلفة." },
  { id: 15, arabic: "الغَفَّارُ", english: "Al-Ghaffar", meaning: "الكثير المغفرة، الذي يستر الذنوب ويتجاوز عنها." },
  { id: 16, arabic: "القَهَّارُ", english: "Al-Qahhar", meaning: "الذي قهر الجبابرة، وذلت لعظمته الرقاب." },
  { id: 17, arabic: "الوَهَّابُ", english: "Al-Wahhab", meaning: "كثير الهبات والعطايا، يعطي بغير سؤال ولا عوض." },
  { id: 18, arabic: "الرَّزَّاقُ", english: "Ar-Razzaq", meaning: "الذي وسع رزقه المخلوقات كلها." },
  { id: 19, arabic: "الفَتَّاحُ", english: "Al-Fattah", meaning: "الذي يفتح أبواب الرحمة والرزق لعباده، ويحكم بينهم بالحق." },
  { id: 20, arabic: "العَلِيمُ", english: "Al-Aleem", meaning: "الذي أحاط علمه بكل شيء، ظاهره وباطنه." },
  { id: 21, arabic: "القَابِضُ", english: "Al-Qabid", meaning: "الذي يقبض الرزق والأرواح عمن يشاء بحكمته." },
  { id: 22, arabic: "البَاسِطُ", english: "Al-Basit", meaning: "الذي يبسط الرزق لمن يشاء بجوده ورحمته." },
  { id: 23, arabic: "الخَافِضُ", english: "Al-Khafid", meaning: "الذي يخفض الكفار بالإذلال، ويخفض من يشاء بعدله." },
  { id: 24, arabic: "الرَّافِعُ", english: "Ar-Rafi'", meaning: "الذي يرفع المؤمنين بالإعزاز، ويرفع درجاتهم." },
  { id: 25, arabic: "المُعِزُّ", english: "Al-Mu'izz", meaning: "الذي يهب العز لمن يشاء." },
  { id: 26, arabic: "المُذِلُّ", english: "Al-Mudhill", meaning: "الذي يذل من يشاء من أعدائه." },
  { id: 27, arabic: "السَّمِيعُ", english: "As-Sami'", meaning: "الذي وسع سمعه كل الأصوات، لا يشغله سمع عن سمع." },
  { id: 28, arabic: "البَصِيرُ", english: "Al-Basir", meaning: "الذي يرى كل شيء وإن دق وصغر، لا يخفى عليه شيء." },
  { id: 29, arabic: "الحَكَمُ", english: "Al-Hakam", meaning: "الذي يحكم بين خلقه، ولا معقب لحكمه." },
  { id: 30, arabic: "العَدْلُ", english: "Al-'Adl", meaning: "المنزه عن الظلم والجور في حكمه وفعله." },
  { id: 31, arabic: "اللَّطِيفُ", english: "Al-Latif", meaning: "البر بعباده، العالم بخفايا الأمور ودقائقها." },
  { id: 32, arabic: "الخَبِيرُ", english: "Al-Khabir", meaning: "العالم ببواطن الأمور وحقائقها." },
  { id: 33, arabic: "الحَلِيمُ", english: "Al-Halim", meaning: "الذي لا يعاجل بالعقوبة، ويصفح مع القدرة." },
  { id: 34, arabic: "العَظِيمُ", english: "Al-Azim", meaning: "الذي له كمال العظمة في ذاته وصفاته." },
  { id: 35, arabic: "الغَفُورُ", english: "Al-Ghafur", meaning: "الذي يكثر من ستر الذنوب والتجاوز عنها." },
  { id: 36, arabic: "الشَّكُورُ", english: "Ash-Shakur", meaning: "الذي يجازي على اليسير من الطاعة بالكثير من الثواب." },
  { id: 37, arabic: "العَلِيُّ", english: "Al-Aliyy", meaning: "الذي له العلو المطلق، علو الذات والقدر والقهر." },
  { id: 38, arabic: "الكَبِيرُ", english: "Al-Kabir", meaning: "الذي هو أكبر من كل شيء، وله الكبرياء في السماوات والأرض." },
  { id: 39, arabic: "الحَفِيظُ", english: "Al-Hafiz", meaning: "الذي يحفظ خلقه من الهلاك، ويحفظ أعمالهم." },
  { id: 40, arabic: "المُقِيتُ", english: "Al-Muqit", meaning: "المقتدر، والرازق الذي يوصل الأقوات إلى الخلق." },
  { id: 41, arabic: "الحَسِيبُ", english: "Al-Hasib", meaning: "الكافي لعباده، والمحاسب لهم على أعمالهم." },
  { id: 42, arabic: "الجَلِيلُ", english: "Al-Jalil", meaning: "المتصف بصفات الجلال والعظمة." },
  { id: 43, arabic: "الكَرِيمُ", english: "Al-Karim", meaning: "الكثير الخير، الجواد المعطي الذي لا ينفد عطاؤه." },
  { id: 44, arabic: "الرَّقِيبُ", english: "Ar-Raqib", meaning: "الحافظ الذي لا يغيب عنه شيء، المطلع على ما في الضمائر." },
  { id: 45, arabic: "المُجِيبُ", english: "Al-Mujib", meaning: "الذي يقابل الدعاء والسؤال بالعطاء والقبول." },
  { id: 46, arabic: "الوَاسِعُ", english: "Al-Wasi'", meaning: "الذي وسعت رحمته وعلمه ورزقه كل شيء." },
  { id: 47, arabic: "الحَكِيمُ", english: "Al-Hakim", meaning: "الذي يضع الأشياء في مواضعها، ولا يفعل إلا الصواب." },
  { id: 48, arabic: "الوَدُودُ", english: "Al-Wadud", meaning: "المحب لأوليائه، المحبوب لهم." },
  { id: 49, arabic: "المَجِيدُ", english: "Al-Majid", meaning: "الواسع الكرم، العظيم القدر." },
  { id: 50, arabic: "البَاعِثُ", english: "Al-Ba'ith", meaning: "الذي يبعث الخلق بعد الموت للحساب والجزاء." },
  { id: 51, arabic: "الشَّهِيدُ", english: "Ash-Shahid", meaning: "المطلع على كل شيء، الحاضر الذي لا يغيب." },
  { id: 52, arabic: "الحَقُّ", english: "Al-Haqq", meaning: "الثابت الوجود، الذي لا شك في ألوهيته." },
  { id: 53, arabic: "الوَكِيلُ", english: "Al-Wakil", meaning: "القائم بأمور خلقه، الكفيل بأرزاقهم." },
  { id: 54, arabic: "القَوِيُّ", english: "Al-Qawiyy", meaning: "التام القوة، الذي لا يعجزه شيء." },
  { id: 55, arabic: "المَتِينُ", english: "Al-Matin", meaning: "الشديد القوة الذي لا يلحقه تعب ولا إعياء." },
  { id: 56, arabic: "الوَلِيُّ", english: "Al-Waliyy", meaning: "الناصر والمؤيد والمحب لأوليائه." },
  { id: 57, arabic: "الحَمِيدُ", english: "Al-Hamid", meaning: "المستحق للحمد والثناء على ذاته وصفاته وأفعاله." },
  { id: 58, arabic: "المُحْصِي", english: "Al-Muhsi", meaning: "الذي أحاط بكل شيء علماً، وأحصى كل شيء عدداً." },
  { id: 59, arabic: "المُبْدِئُ", english: "Al-Mubdi'", meaning: "الذي بدأ الخلق وأوجده من العدم." },
  { id: 60, arabic: "المُعِيدُ", english: "Al-Mu'id", meaning: "الذي يعيد الخلق بعد الموت." },
  { id: 61, arabic: "المُحْيِي", english: "Al-Muhyi", meaning: "الذي يحيي الأجسام بإنشاء الأرواح فيها، ويحيي القلوب بالمعرفة." },
  { id: 62, arabic: "المُمِيتُ", english: "Al-Mumit", meaning: "الذي يقدر الموت على خلقه." },
  { id: 63, arabic: "الحَيُّ", english: "Al-Hayy", meaning: "الذي له الحياة الكاملة الباقية التي لا زوال لها." },
  { id: 64, arabic: "القَيُّومُ", english: "Al-Qayyum", meaning: "القائم بنفسه المقيم لغيره، لا يزول ولا يحول." },
  { id: 65, arabic: "الوَاجِدُ", english: "Al-Wajid", meaning: "الذي يجد كل ما يطلبه ويريده، الغني الذي لا يفتقر." },
  { id: 66, arabic: "المَاجِدُ", english: "Al-Majid", meaning: "كثير الإحسان والفضل والمجد." },
  { id: 67, arabic: "الوَاحِدُ", english: "Al-Wahid", meaning: "المتفرد في ذاته وصفاته وأفعاله، لا شريك له." },
  { id: 68, arabic: "الصَّمَدُ", english: "As-Samad", meaning: "السيد المقصود في الحوائج، الذي لا جوف له." },
  { id: 69, arabic: "القَادِرُ", english: "Al-Qadir", meaning: "الذي له القدرة الكاملة، يفعل ما يشاء." },
  { id: 70, arabic: "المُقْتَدِرُ", english: "Al-Muqtadir", meaning: "المتمكن من الفعل، لا يمتنع عليه شيء." },
  { id: 71, arabic: "المُقَدِّمُ", english: "Al-Muqaddim", meaning: "الذي يقدم من يشاء بحكمته وتوفيقه." },
  { id: 72, arabic: "المُؤَخِّرُ", english: "Al-Mu'akhkhir", meaning: "الذي يؤخر من يشاء بحكمته وعدله." },
  { id: 73, arabic: "الأَوَّلُ", english: "Al-Awwal", meaning: "الذي ليس قبله شيء." },
  { id: 74, arabic: "الآخِرُ", english: "Al-Akhir", meaning: "الذي ليس بعده شيء." },
  { id: 75, arabic: "الظَّاهِرُ", english: "Az-Zahir", meaning: "الذي ليس فوقه شيء، العالي على خلقه." },
  { id: 76, arabic: "البَاطِنُ", english: "Al-Batin", meaning: "الذي ليس دونه شيء، العالم ببواطن الأمور." },
  { id: 77, arabic: "الوَالِي", english: "Al-Wali", meaning: "المالك للأشياء، المتصرف فيها." },
  { id: 78, arabic: "المُتَعَالِي", english: "Al-Muta'ali", meaning: "المنزه عن صفات الخلق، المرتفع عن كل نقص." },
  { id: 79, arabic: "البَرُّ", english: "Al-Barr", meaning: "الرحيم بعباده، المحسن إليهم." },
  { id: 80, arabic: "التَّوَّابُ", english: "At-Tawwab", meaning: "الذي يقبل توبة عباده، ويوفقهم لها." },
  { id: 81, arabic: "المُنْتَقِمُ", english: "Al-Muntaqim", meaning: "الذي يعاقب العصاة على ما اجترحوه من الآثام." },
  { id: 82, arabic: "العَفُوُّ", english: "Al-Afuww", meaning: "الذي يمحو السيئات ويتجاوز عن المعاصي." },
  { id: 83, arabic: "الرَّؤُوفُ", english: "Ar-Ra'uf", meaning: "الشديد الرحمة والرأفة بعباده." },
  { id: 84, arabic: "مَالِكُ المُلْكِ", english: "Malik-ul-Mulk", meaning: "المتصرف في ملكه كيف يشاء." },
  { id: 85, arabic: "ذُو الجَلَالِ وَالإِكْرَامِ", english: "Dhul-Jalal wal-Ikram", meaning: "صاحب العظمة والكبرياء، والفضل والإحسان." },
  { id: 86, arabic: "المُقْسِطُ", english: "Al-Muqsit", meaning: "العادل في حكمه، المنصف للمظلوم من الظالم." },
  { id: 87, arabic: "الجَامِعُ", english: "Al-Jami'", meaning: "الذي يجمع الخلائق ليوم لا ريب فيه." },
  { id: 88, arabic: "الغَنِيُّ", english: "Al-Ghaniyy", meaning: "المستغني عن الخلق، وكل الخلق مفتقر إليه." },
  { id: 89, arabic: "المُغْنِي", english: "Al-Mughni", meaning: "الذي يغني من يشاء من عباده." },
  { id: 90, arabic: "المَانِعُ", english: "Al-Mani'", meaning: "الذي يمنع ما يشاء عمن يشاء، ويحمي أولياءه." },
  { id: 91, arabic: "الضَّارُّ", english: "Ad-Darr", meaning: "المقدر للضر على من يشاء بحكمته." },
  { id: 92, arabic: "النَّافِعُ", english: "An-Nafi'", meaning: "المقدر للنفع لمن يشاء برحمته." },
  { id: 93, arabic: "النُّورُ", english: "An-Nur", meaning: "الذي نور السماوات والأرض، وهدى قلوب المؤمنين." },
  { id: 94, arabic: "الهَادِي", english: "Al-Hadi", meaning: "المرشد لعباده إلى طريق الحق والخير." },
  { id: 95, arabic: "البَدِيعُ", english: "Al-Badi'", meaning: "خالق الأشياء على غير مثال سابق، المبدع في خلقه." },
  { id: 96, arabic: "البَاقِي", english: "Al-Baqi", meaning: "الدائم الوجود الذي لا فناء له." },
  { id: 97, arabic: "الوَارِثُ", english: "Al-Warith", meaning: "الذي يرث الأرض ومن عليها بعد فناء الخلق." },
  { id: 98, arabic: "الرَّشِيدُ", english: "Ar-Rashid", meaning: "الذي يرشد الخلق إلى مصالحهم، الحكيم في تدبيره." },
  { id: 99, arabic: "الصَّبُورُ", english: "As-Sabur", meaning: "الذي لا يعاجل العصاة بالعقوبة، ويمهلهم للتوبة." }
];
